language: "haskell"
sudo: required
dist: trusty

install:
  # stack
  - mkdir -p ~/.local/bin
  - travis_retry curl -sSL https://get.haskellstack.org/ | sh
  - export PATH=~/.local/bin:$PATH
  - stack --no-terminal --version

script:
  - sudo rm -rf /opt/cabal
  - stack setup --no-terminal
  - stack update --no-terminal
  - stack build
  - mkdir static
  - rm -f static/*
  - cp $(stack path --local-install-root)/bin/*.jsexe/* static


cache:
  timeout: 2000
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.stack
  - .stack-work/
  apt: true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: static
  repo: junjihashimoto/miso-snake
  on:
    branch: master
